### ISSUE TITLE
__vsnprintf_chk: symbol not found in image ruby:3.3.4-alpine3.20

### ISSUE THREAD

**Issue by fguillen** [ankane/informers#12]
When I execute this line in a Docker image `ruby:3.3.4-alpine3.20`

```
Informers.pipeline("embedding", "sentence-transformers/all-MiniLM-L6-v2")
```

I get this error:

```
I, [2024-12-05T20:49:55.365882 #9]  INFO -- : [62709cc1-e351-4573-a1ce-3f2ca6e48fa3] [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=0fbf0811-7b79-4246-80cd-11f99480882e (only available if report was successful)
E, [2024-12-05T20:49:55.366954 #9] ERROR -- : [62709cc1-e351-4573-a1ce-3f2ca6e48fa3]   
[62709cc1-e351-4573-a1ce-3f2ca6e48fa3] LoadError (Could not open library '/usr/local/bundle/gems/onnxruntime-0.9.3-x86_64-linux/vendor/libonnxruntime.so': Error relocating /usr/local/bundle/gems/onnxruntime-0.9.3-x86_64-linux/vendor/libonnxruntime.so: __vsnprintf_chk: symbol not found.
Searched in <system library path>):
[62709cc1-e351-4573-a1ce-3f2ca6e48fa3] 
Causes:
[62709cc1-e351-4573-a1ce-3f2ca6e48fa3] LoadError (Could not open library '/usr/local/bundle/gems/onnxruntime-0.9.3-x86_64-linux/vendor/libonnxruntime.so': Error relocating /usr/local/bundle/gems/onnxruntime-0.9.3-x86_64-linux/vendor/libonnxruntime.so: __vsnprintf_chk: symbol not found.
Searched in <system library path>)
[62709cc1-e351-4573-a1ce-3f2ca6e48fa3]   
[62709cc1-e351-4573-a1ce-3f2ca6e48fa3] app/services/user_favorites/generate_embeddings.rb:3:in `perform'
```

This is the Dockerfile:

```
FROM ruby:3.3.4-alpine3.20

# Install dependencies
RUN apk update --no-cache
RUN apk upgrade

RUN apk add --no-cache build-base git curl
RUN apk add --no-cache bash libstdc++ zlib pkgconfig autoconf automake libtool nasm
RUN apk add --no-cache tzdata nodejs npm openjdk8 libxml2 libxslt gcompat imagemagick
RUN apk add --no-cache gifsicle jpegoptim libpng libjpeg-turbo libjpeg-turbo-utils optipng pngcrush pngquant
RUN apk add --no-cache advancecomp --repository http://dl-cdn.alpinelinux.org/alpine/edge/community
RUN apk add --no-cache jhead --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
RUN npm install -g --force --unsafe-perm=true --allow-root svgo advpng-bin
RUN apk add --update --no-cache openssh

# For mysql
RUN apk add --no-cache mariadb-dev

# Install postgresql dependencies
RUN apk add libpq-dev

# Set an environment variable where the Rails app is installed to inside of Docker image:
ENV RAILS_ROOT /var/www/app
RUN mkdir -p $RAILS_ROOT

# Set working directory, where the commands will be ran:
WORKDIR $RAILS_ROOT

# Setting env up
ENV RAILS_ENV="production"
ENV RACK_ENV="production"

# Basic folders (required by puma)
RUN mkdir -p tmp/pids
RUN mkdir -p tmp/sockets

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN bundle install --jobs 1 --retry 2 --without development test

# Adding project files
COPY . .
# RUN bundle exec rails assets:precompile

EXPOSE 3000
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]

```

Thanks for the support

**Comment by fguillen** [comment]
In another Docker image (same configuration) the error is: 

```
onnx/model.onnx |████████████████████████████████████████████████████████████████████████████████████████████████████|
/usr/local/bundle/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': Could not open library '/usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/vendor/libonnxruntime.arm64.so': Error relocating /usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/vendor/libonnxruntime.arm64.so: __getauxval: symbol not found. (LoadError)
Searched in <system library path>
/usr/local/bundle/gems/ffi-1.17.0-aarch64-linux-musl/lib/ffi/dynamic_library.rb:94:in `load_library': Could not open library '/usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/vendor/libonnxruntime.arm64.so': Error relocating /usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/vendor/libonnxruntime.arm64.so: __getauxval: symbol not found. (LoadError)
Searched in <system library path>
	from /usr/local/bundle/gems/ffi-1.17.0-aarch64-linux-musl/lib/ffi/library.rb:95:in `block in ffi_lib'
	from /usr/local/bundle/gems/ffi-1.17.0-aarch64-linux-musl/lib/ffi/library.rb:94:in `map'
	from /usr/local/bundle/gems/ffi-1.17.0-aarch64-linux-musl/lib/ffi/library.rb:94:in `ffi_lib'
	from /usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/lib/onnxruntime/ffi.rb:5:in `<module:FFI>'
	from /usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/lib/onnxruntime/ffi.rb:2:in `<module:OnnxRuntime>'
	from /usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/lib/onnxruntime/ffi.rb:1:in `<main>'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/lib/onnxruntime/inference_session.rb:313:in `api'
	from /usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/lib/onnxruntime/inference_session.rb:301:in `api'
	from /usr/local/bundle/gems/onnxruntime-0.9.3-aarch64-linux/lib/onnxruntime/inference_session.rb:8:in `initialize'
	from /usr/local/bundle/gems/informers-1.2.0/lib/informers/models.rb:201:in `new'
	from /usr/local/bundle/gems/informers-1.2.0/lib/informers/models.rb:201:in `construct_session'
	from /usr/local/bundle/gems/informers-1.2.0/lib/informers/models.rb:171:in `from_pretrained'
```

**Comment by ankane** [comment]
Hi @fguillen, the shared library included in the ONNX Runtime gem requires glibc (and Alpine uses musl). You can try using [gcompat](https://wiki.alpinelinux.org/wiki/Running_glibc_programs), or use the non-Alpine Ruby image.

**Comment by fguillen** [comment]
Hi @ankane wow, thanks for the quick answer. I found my way. Let me know if you think is the right one:

It looks like the issue belongs to the dependency `onnxruntime`.

Here is the solution: https://github.com/microsoft/onnxruntime/issues/8162#issuecomment-1623120734

Add this to the Dockerfile

```
RUN apk add --no-cache onnxruntime --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ -X http://dl-cdn.alpinelinux.org/alpine/edge/community/ -X http://dl-cdn.alpinelinux.org/alpine/edge/main
```

And, in the ruby code:

```
OnnxRuntime.ffi_lib = "path/to/lib/libonnxruntime.so"
```

**Comment by ankane** [comment]
That should work as well (although you'll likely want to make sure the version of shared library matches the one included in the version of the gem you're using).

**Comment by fguillen** [comment]
> That should work as well (although you'll likely want to make sure the version of shared library matches the one included in the version of the gem you're using).

Sorry, I am not sure how can I confirm this. This is what I find in my Gemfile.lock:

```
> cat Gemfile.lock | grep informers
    informers (1.2.0)
  informers

> cat Gemfile.lock | grep onnx     
      onnxruntime (>= 0.9)
    onnxruntime (0.9.3-aarch64-linux)
    onnxruntime (0.9.3-arm64-darwin)
    onnxruntime (0.9.3-x86_64-darwin)
    onnxruntime (0.9.3-x86_64-linux)
```

And this is the version of the shared library:

```
libonnxruntime.so.1.19.2
```

Is this a problem?

**Comment by ankane** [comment]
You'll need to check the [changelog](https://github.com/ankane/onnxruntime-ruby/blob/master/CHANGELOG.md) for [onnxruntime-ruby](https://github.com/ankane/onnxruntime-ruby).

**Comment by fguillen** [comment]
Oh!, perfect, I see. I have to use `onnxruntime` version `0.9.2`:

```
0.9.2 (2024-09-04)
Updated ONNX Runtime to 1.19.2
```

Thanks!
